from __future__ import annotations

import re
from typing import List, Tuple

from qtguard_core.schema import QTGuardOutput

# Required inputs for a minimally safe QT triage (demo guardrails)
_REQUIRED_PATTERNS: List[Tuple[str, re.Pattern]] = [
    ("QTc", re.compile(r"\bqtc\b|\bqt\s*c\b|\bqt interval\b", re.IGNORECASE)),
    # Safer than r"\bK\b" / r"\bMg\b": looks for explicit lab notation like K=3.1 or Mg:1.6,
    # while still accepting the full words "potassium"/"magnesium".
    ("Potassium (K)", re.compile(r"\bpotassium\b|\bK\s*[:=]\s*\d", re.IGNORECASE)),
    ("Magnesium (Mg)", re.compile(r"\bmagnesium\b|\bMg\s*[:=]\s*\d", re.IGNORECASE)),
]

# Optional but helpful (kept for future extension)
_OPTIONAL_PATTERNS: List[Tuple[str, re.Pattern]] = [
    ("Heart rate (HR)", re.compile(r"\bHR\b|\bheart rate\b", re.IGNORECASE)),
]


def find_missing_inputs(mini_chart: str) -> List[str]:
    """Lightweight missing-data detector for the demo scaffold."""
    text = mini_chart or ""
    missing: List[str] = []
    for label, pattern in _REQUIRED_PATTERNS:
        if not pattern.search(text):
            missing.append(label)
    return missing


def build_safe_output(mini_chart: str) -> QTGuardOutput:
    """
    If missing required fields, return a deferral output.
    Otherwise call MedGemma (HAI-DEF) to generate a structured plan.
    """
    missing = find_missing_inputs(mini_chart)
    if missing:
        return QTGuardOutput.deferral(missing)

    # Inputs present -> call MedGemma
    try:
        from qtguard_core.inference import generate_qtguard_output

        out = generate_qtguard_output(mini_chart)
        # Add a small audit note that MedGemma was used
        out.audit_view.notes.append("Generated by MedGemma (HAI-DEF) with JSON schema validation.")
        return out

    except Exception as e:
        # Safe fallback if inference fails
        fallback = QTGuardOutput(
            risk_summary="Inputs appear present, but model inference failed. Returning safe placeholder output.",
            action_plan=[
                "Re-run the generation. If the issue persists, confirm model access/terms and hardware capacity.",
                "Do not make medication changes based solely on this tool output.",
            ],
            patient_counseling=(
                "This tool could not generate guidance at this time. Please ask your care team to review the case."
            ),
            audit_view={
                "missing_data": [],
                "notes": [
                    "Guardrails check passed for required inputs (QTc, K, Mg).",
                    f"MedGemma inference error: {type(e).__name__}: {e}",
                ],
            },
        )
        return fallback

